### ISSUE TITLE
Review eigen build and fix install

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#321]
Experiencing some issues with the current `eigen` build and change the installation to run on `ninja` rather than `make`. Additionally, it might be a good idea to port the repo from Gitlab to Github.

**To-Do:**
* [ ] Migrate repo from [Gitlab](https://gitlab.com/shillaker/eigen) to Github (faasm/eigen).
* [ ] Double check the current build works on 20.04.
* [ ] Change installation script in `faasm/faasmcli/faasmcli/tasks/libs.py` to use `ninja` rather than `make`.

**Comment by Shillaker** [comment]
Looks good, this should be captured in #314 though, so I'll add a note in there and close this one.
